# Generated by Django 4.1.7 on 2023-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('client', 'Заказчик'), ('freelancer', 'Фрилансер')], max_length=30, verbose_name='Роль'),
        ),
    ]
