# Generated by Django 4.1.7 on 2023-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0003_customuser_tg_id'), ('users', '0004_alter_customuser_tg_id')]

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(blank=True, verbose_name='ID в Telegram'),
        ),
    ]
