# Generated by Django 4.1.7 on 2023-02-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='ID в Telegram'),
            preserve_default=False,
        ),
    ]
