# Generated by Django 4.1.7 on 2023-02-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(blank=True, verbose_name='ID в Telegram'),
        ),
    ]
