# Generated by Django 4.1.7 on 2023-02-22 09:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
                ('max_requests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Заявок в месяц')),
                ('response_time', models.DurationField(default=datetime.timedelta(seconds=43200), verbose_name='Время на ответ')),
                ('bind_freelancer', models.BooleanField(db_index=True, default=False, verbose_name='Возможность закрепить фрилансера')),
                ('see_contacts', models.BooleanField(db_index=True, default=False, verbose_name='Возможность увидеть контакты фрилансера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
