# Generated by Django 4.1.7 on 2023-02-22 10:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/%Y/%m/%d', verbose_name='Приложение')),
                ('done', models.BooleanField(db_index=True, default=False, verbose_name='Заявка закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.CharField(max_length=30, verbose_name='Автор - заглушка')),
                ('freelancer', models.CharField(blank=True, max_length=30, verbose_name='Фрилансер - заглушка')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
                ('max_requests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Заявок в месяц')),
                ('response_time', models.DurationField(default=datetime.timedelta(seconds=43200), verbose_name='Время на ответ')),
                ('bind_freelancer', models.BooleanField(db_index=True, default=False, verbose_name='Возможность закрепить фрилансера')),
                ('see_contacts', models.BooleanField(db_index=True, default=False, verbose_name='Возможность увидеть контакты фрилансера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
