# Generated by Django 4.1.7 on 2023-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('support_bot', '0002_request'), ('support_bot', '0003_alter_request_options'), ('support_bot', '0004_alter_request_options')]

    dependencies = [
        ('support_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/%Y/%m/%d', verbose_name='Приложение')),
                ('done', models.BooleanField(db_index=True, default=False, verbose_name='Заявка закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.CharField(max_length=30, verbose_name='Автор - заглушка')),
                ('freelancer', models.CharField(blank=True, max_length=30, verbose_name='Фрилансер - заглушка')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('created_at',),
            },
        ),
    ]
